# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.

from functions import is_even


def get_fibonacci_nums(n):
    nums = [0, 1]
    while nums[-1] < n:
        nums.append(nums[-1] + nums[-2])
    return nums


def main():
    print(sum(filter(is_even, get_fibonacci_nums(4000000))))


if __name__ == '__main__':
    main()
